### ISSUE TITLE
There is no possibility to distinguish `redeem` and `withdraw` calls from events

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/metamorpho#318]
It is impossible to retrieve the called function from the Withraw event, and there is the same issue with the deposit/mint functions.

In some way, this is a limitation of the ERC4626 standard, but I want to mention it somewhere to keep a trace of it.

This limitation can be an issue if you want to make statistics about the usage of shares vs amounts to interact with a vault. 

BTW, there is the same issue on Blue, and we need to find out from events if shares or assets are used.

**Comment by Rubilmax** [comment]
I think it's fine because there is always something more to log if we want to support different kinds of statistics
In this case, studying how the vault is used is better to be studied by indexing txs and looking for internal CALLs to the vault, to see how it is called. It's a win-win: we don't log overwhelming data and it's easier to access any kind of statistics (Dune being built for that right?)

**Comment by julien-devatom** [comment]
This is not really true since redeem & withdraw have two different paradigms: you sell shares or you buy back assets. IMO it's a bit like exactAmountIn/exactAmountOut of uniswap.

So this is not only for statistics, this is also to distinguish these two different actions.  

On the other points (dune etc) you're right!

Closing it since it is not worth discussing more on it, ty for your comment!
