### ISSUE TITLE
Proposal for additional verification specs

### ISSUE THREAD

**Issue by daejunpark** [morpho-org/metamorpho#412]
In addition to the [existing specs](https://github.com/morpho-org/metamorpho/tree/398c553b06769fc3a84d044c4d1f097de77a8548/certora), the following specs could also be considered. If the prover is incapable of verifying them, fuzzing could be considered as an alternative.

1. **[Share Price Preservation]:** For any tx: the share price, `totalAssets() / totalSupply()`, does _not_ decrease.
   - That is, the price immediately before the tx must be less than or equal to the price immediately after the tx.
   - Note: this spec ensures the correctness of accounting logic, e.g., interest and fees are accurately accounted for, the share price is properly updated prior to converting asset amounts to/from shares, etc.

1. **[ERC4626]:** The ERC4626 properties, especially the [round-trip properties](https://github.com/a16z/erc4626-tests/blob/main/ERC4626.prop.sol#L244-L318), hold.

1. **[Consistency of lastTotalAssets]:** After any tx: `lastTotalAssets == totalAssets()`
   - Small discrepancies may exist due to rounding errors.

1. **[Soft Supply Cap]:** For any tx, for any market: if the supply increases, then it must _not_ exceed the supply cap.
   - Note: the supply cap may be updated to be below the current supply, thus the supply may exceed the cap temporarily. However, it is not allowed to add further supply once it exceeds the cap. Moreover, the excessive supply may be partially withdrawn, where the remaining supply may still exceed the cap.

1. **[Consistency between supplyQueue and withdrawQueue]:** If "`set(supplyQueue) - set(withdrawQueue)`" is non-emtpy, then their cap is zero, with no pending cap.
   - Note: ideally, supplyQueue should be a subset of withdrawQueue. However, a market may be removed from withdrawQueue without updating supplyQueue. That's why certain markets may appear only in supplyQueue. However, the supply cap of such markets must be zero, because of the condition for removal from withdrawQueue.

1. **[Consistency of withdrawQueue]:** A market whose cap > 0 must be included in the withdraw queue.
   - Note: this is the converse of the existing spec [`inWithdrawQueueIsEnabled`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/Enabled.spec#L13).

1. **[Consistency of Market Config]:** For any market config:
   - If it's _not_ enabled, then cap == 0 (although a pending cap may exist). That is, if cap > 0, then it's enabled.
     - Note: this has been captured by the existing spec [`supplyCapIsEnabled`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/ConsistentState.spec#L21).
   - If removableAt > 0, then cap == 0 (with no pending), and it's enabled.
     - Note: this has been _partially_ captured by the existing specs [`supplyCapIsNotMarkedForRemoval`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/ConsistentState.spec#L57) and [`pendingCapIsNotMarkedForRemoval`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/ConsistentState.spec#L65). To fully capture, an additional spec is needed: `!config.enabled => config.removableAt == 0;`.

**Comment by QGarchery** [comment]
Thanks a lot for the ideas ! Here are some thoughts about them:
1. The share price could decrease if there is some bad debt on some market. So to capture your idea where you compare with the price immediately before the tx, we could do a dummy transaction first.
2. Good point, this seems like a hard property to prove but a nice one. We have had some troubles with the math operations in the past on metamorpho
3. Same, tough to specify that cleanly too. How do you account for those small rounding errors in the spec ?
4. Thought about this one, and it is in #333. I found some exceptions (donations and interest accrual) which makes it a bit difficult to specify it
5. I think it's already covered because any market that is not in the withdraw queue is not enabled (rule [`enabledIsInWithdrawQueue`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/Enabled.spec#L57)) and every market that is not enabled has 0 cap (invariant [`supplyCapIsEnabled`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/ConsistentState.spec#L21))
6. I think it's covered by the rule [`enabledIsInWithdrawQueue`](https://github.com/morpho-org/metamorpho/blob/398c553b06769fc3a84d044c4d1f097de77a8548/certora/specs/Enabled.spec#L57)
7. Nice catch !

**Comment by QGarchery** [comment]
Closing this as 4-7 have been completed, 3 is dropped because it seems difficult to specify, and 1 & 2 have been added to #333
